var SHEET_URL='https://script.google.com/macros/s/AKfycbzuHMy4bSzBuXSdwYRslZjr9SPD6JkrkPbzanq7qUENahu2yXrgIvpmDXh1f-v3Rugm/exec';
var EMAIL_RE=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
var _pageBorn=Date.now();

function animateCount(el,target,ms){if(!el)return;var v=0,step=target/(ms/16);var t=setInterval(function(){v+=step;if(v>=target){el.textContent=target;clearInterval(t);return;}el.textContent=Math.floor(v);},16);}

(function(){var stats=document.querySelector('.stats');if(!stats)return;var ob=new IntersectionObserver(function(entries){if(entries[0].isIntersecting){animateCount(document.getElementById('cnt'),247,1400);ob.disconnect();}});ob.observe(stats);})();

async function join(n){var inp=document.getElementById('em'+n);if(!inp)return;var email=inp.value.trim();if(!email||!EMAIL_RE.test(email)){inp.classList.add('err');var prev=inp.placeholder;inp.placeholder='Please enter a valid email ↑';inp.value='';setTimeout(function(){inp.classList.remove('err');inp.placeholder=prev;},2500);inp.focus();return;}var pill=inp.closest('.wl-pill,.cta-row');var hp=pill?pill.querySelector('.hp-trap'):null;if(hp&&hp.value)return;if(Date.now()-_pageBorn<1200)return;var btn=pill?pill.querySelector('button'):null;if(btn){btn.innerHTML='…';btn.disabled=true;}try{await fetch(SHEET_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({email:email,hp:hp?hp.value:'',source:'mydynasty.app',ts:new Date().toISOString()})});}catch(err){}var el=document.getElementById('cnt');var newCount=(parseInt(el&&el.textContent,10)||247)+1;if(el)el.textContent=newCount;if(n===1){var main=document.getElementById('wlMain');if(main)main.style.display='none';var ok=document.getElementById('wlOk');if(ok)ok.classList.add('visible');var sc=document.getElementById('scCount');if(sc)sc.textContent=newCount;if(window.confetti){confetti({particleCount:90,spread:70,origin:{y:.55},colors:['#f97316','#ea580c','#fbbf24','#fb923c','#fed7aa']});}}else{inp.value='';inp.placeholder='✓ You’re on the list!';inp.style.color='var(--accent)';if(btn)btn.innerHTML='✓';}}

(function(){var em1=document.getElementById('em1');if(em1)em1.addEventListener('keydown',function(e){if(e.key==='Enter')join(1);});var form=document.getElementById('contactForm');if(!form)return;form.addEventListener('submit',async function(e){e.preventDefault();var name=(document.getElementById('cf-name')||{}).value||'';var email=(document.getElementById('cf-email')||{}).value||'';var message=(document.getElementById('cf-message')||{}).value||'';name=name.trim();email=email.trim();message=message.trim();if(!name||!email||!message)return;var btn=this.querySelector('.cf-btn');if(btn){btn.textContent='…';btn.disabled=true;}try{await fetch(SHEET_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({email:email,name:name,message:message,source:'contact-form',ts:new Date().toISOString()})});}catch(err){}this.innerHTML='<div class="cf-ok"><div class="cf-ok-icon">✓</div><div class="cf-ok-title">Message sent!</div><div class="cf-ok-sub">We’ll get back to you soon</div></div>';});})();
